In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_excel(r'D:\MY DATA\DATA\DSA\iris.xlsx')

In [5]:
df.head()

SL   SW   PL   PW Classification
0  5.1  3.5  1.4  0.2    Iris-setosa
1  4.9  3.0  1.4  0.2    Iris-setosa
2  4.7  3.2  1.3  0.2    Iris-setosa
3  4.6  3.1  1.5  0.2    Iris-setosa
4  5.0  3.6  1.4  0.2    Iris-setosa

In [7]:
df.columns

Index(['SL', 'SW', 'PL', 'PW', 'Classification'], dtype='object')

In [9]:
df.isna().sum()

SL                0
SW                0
PL                0
PW                0
Classification    0
dtype: int64

In [11]:
df['Classification'].nunique()

3

In [15]:
df['Classification'].value_counts()

Classification
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

In [13]:
from sklearn.preprocessing import LabelEncoder

In [21]:
label_encoder = LabelEncoder()
df['Classification'] = label_encoder.fit_transform(df['Classification'])
df.head()

SL   SW   PL   PW  Classification
0  5.1  3.5  1.4  0.2               0
1  4.9  3.0  1.4  0.2               0
2  4.7  3.2  1.3  0.2               0
3  4.6  3.1  1.5  0.2               0
4  5.0  3.6  1.4  0.2               0

In [23]:
x = df.drop(['Classification'],axis =1)
y = df['Classification']

In [25]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.25,random_state = 42) 

## Logistic Regression

In [29]:
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression()
log_reg = log_reg.fit(x_train,y_train)

In [31]:
y_pred = log_reg.predict(x_test)

In [33]:
y_pred

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0], dtype=int64)

In [35]:
from sklearn.metrics import confusion_matrix,accuracy_score, precision_score,recall_score, f1_score

In [37]:
print("Confusion matrix ", confusion_matrix(y_test,y_pred))

Confusion matrix  [[15  0  0]
 [ 0 11  0]
 [ 0  0 12]]


In [39]:
print("Accuracy is ", accuracy_score(y_test,y_pred))

Accuracy is  1.0


## KNN

In [43]:
from sklearn.neighbors import KNeighborsClassifier

In [47]:
knn = KNeighborsClassifier(n_neighbors = 5, metric = 'euclidean')
knn.fit(x_train,y_train)

KNeighborsClassifier(metric='euclidean')

In [49]:
y_predictions = knn.predict(x_test)

In [51]:
print("Confusion matrix ", confusion_matrix(y_test,y_predictions))

Confusion matrix  [[15  0  0]
 [ 0 11  0]
 [ 0  0 12]]


In [53]:
print('Accuracy is :',accuracy_score(y_test,y_predictions))

Accuracy is : 1.0


In [57]:
x_new = np.array([[5,5.1,3,3.5]])
prediction = knn.predict(x_new)
prediction

C:\Users\AL792\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

## Naive Bayes

In [64]:
from sklearn.preprocessing import scale

In [70]:
features=scale(df[['SL','SW','PL','PW']])
pd.DataFrame(features).describe()

0             1             2             3
count  1.500000e+02  1.500000e+02  1.500000e+02  1.500000e+02
mean  -4.736952e-16 -6.631732e-16  3.315866e-16 -2.842171e-16
std    1.003350e+00  1.003350e+00  1.003350e+00  1.003350e+00
min   -1.870024e+00 -2.438987e+00 -1.568735e+00 -1.444450e+00
25%   -9.006812e-01 -5.877635e-01 -1.227541e+00 -1.181504e+00
50%   -5.250608e-02 -1.249576e-01  3.362659e-01  1.332259e-01
75%    6.745011e-01  5.692513e-01  7.627586e-01  7.905908e-01
max    2.492019e+00  3.114684e+00  1.786341e+00  1.710902e+00

In [72]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(features,y,test_size=0.15)

In [62]:
from sklearn.naive_bayes import GaussianNB

In [76]:
nb=GaussianNB()
nb.fit(x_train,y_train)

GaussianNB()

In [78]:
y_pred=nb.predict(x_test)

In [82]:
print('accuracy:',accuracy_score(y_pred,y_test))
print('precision:',precision_score(y_pred,y_test,average='micro'))

accuracy: 0.9565217391304348
precision: 0.9565217391304348


In [84]:
print("Confusion matrix ", confusion_matrix(y_test,y_pred))

Confusion matrix  [[8 0 0]
 [0 7 0]
 [0 1 7]]


## SVM

In [89]:
from sklearn.svm import SVC

In [91]:
svm_cls = SVC(kernel = 'linear')
svm_cls = svm_cls.fit(x_train,y_train)
y_pred_svm = svm_cls.predict(x_test)

In [93]:
confusion_matrix(y_test,y_pred_svm)

array([[8, 0, 0],
       [0, 7, 0],
       [0, 0, 8]], dtype=int64)

In [95]:
accuracy_score(y_test,y_pred_svm)

1.0

In [97]:
precision_score(y_test,y_pred_svm, average = 'micro')

1.0

## Decision Tree

In [100]:
from sklearn.tree import DecisionTreeClassifier

In [102]:
dt_cls = DecisionTreeClassifier()
dt_cls = dt_cls.fit(x_train,y_train)

In [104]:
y_pred_dt = dt_cls.predict(x_test)

In [106]:
confusion_matrix(y_test,y_pred_dt)

array([[8, 0, 0],
       [0, 7, 0],
       [0, 1, 7]], dtype=int64)

In [108]:
accuracy_score(y_test,y_pred_dt)

0.9565217391304348

In [110]:
precision_score(y_test,y_pred_dt, average = 'micro')

0.9565217391304348

## Random Forest

In [113]:
from sklearn.ensemble import RandomForestClassifier

In [115]:
rf_cls = DecisionTreeClassifier()
rf_cls = rf_cls.fit(x_train,y_train)

In [117]:
y_pred_rf = rf_cls.predict(x_test)

In [119]:
confusion_matrix(y_test,y_pred_rf)

array([[8, 0, 0],
       [0, 7, 0],
       [0, 1, 7]], dtype=int64)

In [121]:
accuracy_score(y_test,y_pred_rf)

0.9565217391304348

In [123]:
precision_score(y_test,y_pred_rf, average = 'micro')

0.9565217391304348

## Logistic Regression, KNN and SVM model gives best result with accuracy 1